doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'

        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        host: '%env(trim:DB_HOST)%'
        port: '%env(trim:DB_PORT)%'
        user: '%env(trim:DB_USER)%'
        password: '%env(trim:DB_PASSWORD)%'
        dbname: '%env(trim:DB_NAME)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
