nelmio_api_doc:
    documentation:
        schemes: [http]
        info:
            title: Records API
            description: RESTful CRUD for managing records & artists
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
