version: "3.8"

services:

  record-api:
    container_name: record-api
    build:
      context: ..
      dockerfile: ./.infra/dev.Dockerfile
    restart: always
    volumes:
      - ..:/var/www:rw

  mysql:
    container_name: record-api-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - record-api-db:/var/lib/mysql

  nginx:
    container_name: record-api-nginx
    image: nginx:alpine
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - record-api
    ports:
      - "80:80"

volumes:
  record-api-db:
